name: badi_date
description: A Baha'i Calendar (Badi Calendar) library to convert dates from and to Georgian Dates.
version: 1.0.0
homepage: https://github.com/Soroosh

environment:
  sdk: ">=2.12.1 <3.0.0"

dependencies:
  dart_suncalc: ^0.2.0

dev_dependencies:
  test: ^1.16.8

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

